.PHONY: config-init config-validate

PYTHON_BIN        ?= python3
VENV_DIR          ?= $(ROOT)/venv-mcp-broker
PYTHON            ?= $(VENV_DIR)/bin/python
PIP               ?= $(VENV_DIR)/bin/pip
MUTMUT            ?= $(VENV_DIR)/bin/mutmut
PIP_UPGRADE       ?= 0
REQUIREMENTS      ?= $(ROOT)/requirements.txt

RUNTIME_ROOT      ?= $(HOME)/mcp/mcp-broker
CONFIG_TEMPLATE_PATH ?= $(ROOT)/config/broker.example.yaml
CONFIG_SCHEMA_PATH ?= $(ROOT)/config/broker.schema.json
CONFIG_PRIVATE_PATH ?= $(ROOT)/config/broker.private.yaml
CONFIG_PATH       ?= $(CONFIG_PRIVATE_PATH)
SOCKET_PATH       ?= $(RUNTIME_ROOT)/sockets/broker.sock
LOG_DIR           ?= $(RUNTIME_ROOT)/logs
STATE_DIR         ?= $(RUNTIME_ROOT)/state
SECRETS_DIR       ?= $(RUNTIME_ROOT)/secrets
CLIENT            ?= codex
PROFILE           ?= codex
NEW_PROFILE       ?= local-client
NEW_CLIENT_FORMAT ?= mcp-settings-json
NEW_CLIENT_CONFIG_PATH ?= $$HOME/.$(NEW_PROFILE)/settings.json
NEW_CLIENT_ENTRY_NAME ?= mcp-broker
NEW_CLIENT_COMMAND ?= mcp-broker-client
NEW_BROKER_TOOL_NAME_STYLE ?= dotted
CONFIG_RENDER_APPLY ?= 0
CONFIG_RENDER_TARGET_PATH ?=
CONFIG_BACKUP_LABEL ?=
CODEX_APP_POLICY_APPLY ?= 0
SECRET_NAME       ?=
FACADE_QUERY      ?=
FACADE_CALL_TOOL  ?=
FACADE_CALL_ARGS  ?=
FACADE_REQUEST_TIMEOUT_SECONDS ?= 70
PARITY_LEFT_PROFILE ?= codex
PARITY_RIGHT_PROFILE ?= claude
DISCOVERY_QUERY   ?= $(FACADE_QUERY)
DISCOVERY_CALL_TOOL ?= $(FACADE_CALL_TOOL)
DISCOVERY_CALL_ARGS ?= $(FACADE_CALL_ARGS)
DEFERRED_ACCEPTANCE_FORMAT ?= markdown
PROJECT_MCP_ROOTS ?= $(HOME)/Projects
PROJECT_MCP_BACKUP_ROOT ?= $(RUNTIME_ROOT)/backups/project-mcp
PROJECT_MCP_APPLY ?= 0
PROJECT_MCP_IMPORT_MISSING ?= 0
PROJECT_MCP_PROFILES ?= codex claude
PROJECT_MCP_CLAUDE_CONFIG ?= $(HOME)/.claude.json
LAUNCHAGENT_APPLY ?= 0
LAUNCHAGENT_LABEL ?= com.mcp-broker.agent
LAUNCHAGENT_DOMAIN ?= gui/$(shell id -u)
LAUNCHAGENT_PLIST ?= $(HOME)/Library/LaunchAgents/$(LAUNCHAGENT_LABEL).plist
SYSTEMD_APPLY    ?= 0
SYSTEMD_SERVICE  ?= mcp-broker.service
SYSTEMD_USER_DIR ?= $(HOME)/.config/systemd/user
SYSTEMD_SERVICE_PATH ?= $(SYSTEMD_USER_DIR)/$(SYSTEMD_SERVICE)
MCP_BROKER_DAEMON_COMMAND ?=
WINDOWS_APPLY    ?= 0
WINDOWS_TASK     ?= mcp-broker
LINUX_SMOKE_IMAGE ?= $(or $(MCP_BROKER_LINUX_SMOKE_IMAGE),python:3-bookworm)
LINUX_RELEASE_GATE_IMAGE ?= $(or $(MCP_BROKER_LINUX_RELEASE_GATE_IMAGE),python:3.13-bookworm)
UNAME_S           := $(shell uname -s)
CPU_COUNT ?= $(shell "$(PYTHON_BIN)" -c 'import os, sys; sys.stdout.write(str(os.cpu_count() or 4))' 2>/dev/null || printf 4)
LOCAL_CPU_BUDGET ?= $(if $(filter Darwin,$(UNAME_S)),2,4)
RELEASE_MUTATION_TARGET ?= $(if $(filter Darwin,$(UNAME_S)),mutation-linux,mutation)
MUTATION_QOS_PREFIX ?= $(if $(filter Darwin,$(UNAME_S)),taskpolicy -b,)

PYTEST_MAXFAIL    ?= 1
PYTEST_TIMEOUT    ?= 30
PYTEST_LIVE_TIMEOUT ?= 300
PYTEST_COV_TIMEOUT ?= $(PYTEST_LIVE_TIMEOUT)
PYTEST_ARGS       ?=
PYTEST_WORKERS ?= $(LOCAL_CPU_BUDGET)
PYTEST_TARGETED_WORKERS ?= 0
PYTEST_FANOUT_WORKERS ?= $(shell "$(PYTHON_BIN)" -c 'import sys; sys.stdout.write(str(max(1, int("$(LOCAL_CPU_BUDGET)") // int("$(TEST_JOBS)"))))' 2>/dev/null || printf 1)
PYTEST_PRECOMMIT_WORKERS ?= $(shell "$(PYTHON_BIN)" -c 'import sys; sys.stdout.write(str(max(1, int("$(LOCAL_CPU_BUDGET)") // int("$(PRECOMMIT_JOBS)"))))' 2>/dev/null || printf 1)
PYTEST_RELEASE_WORKERS ?= $(shell "$(PYTHON_BIN)" -c 'import sys; sys.stdout.write(str(max(1, int("$(LOCAL_CPU_BUDGET)") // int("$(RELEASE_GATE_JOBS)"))))' 2>/dev/null || printf 1)
PYTEST_XDIST_DIST ?= loadfile
PYTEST_MARKER_EXPRESSION ?=
PUBLIC_RELEASE_PYTEST_MARKER_EXPRESSION ?= not private_contract
RELEASE_GATE_PYTEST_MARKER_EXPRESSION ?= $(if $(wildcard $(ROOT)/local.mk),$(PYTEST_MARKER_EXPRESSION),$(if $(strip $(PYTEST_MARKER_EXPRESSION)),$(PYTEST_MARKER_EXPRESSION),$(PUBLIC_RELEASE_PYTEST_MARKER_EXPRESSION)))
QUALITY_GATE_PYTEST_MARKER_EXPRESSION ?= $(RELEASE_GATE_PYTEST_MARKER_EXPRESSION)
PYTEST_MARKER_ARGS ?= $(if $(strip $(PYTEST_MARKER_EXPRESSION)),-m "$(PYTEST_MARKER_EXPRESSION)",)
PYTEST_COV_MARKER_ARGS ?= $(if $(strip $(QUALITY_GATE_PYTEST_MARKER_EXPRESSION)),-m "$(QUALITY_GATE_PYTEST_MARKER_EXPRESSION)",)
PYTEST_XDIST_ARGS ?= $(if $(filter 0,$(PYTEST_WORKERS)),,-n $(PYTEST_WORKERS) --dist $(PYTEST_XDIST_DIST))
PYTEST_TARGETED_XDIST_ARGS ?= $(if $(filter 0,$(PYTEST_TARGETED_WORKERS)),,-n $(PYTEST_TARGETED_WORKERS) --dist $(PYTEST_XDIST_DIST))
TEST_JOBS ?= 4
PRECOMMIT_JOBS ?= 2
RELEASE_GATE_JOBS ?= $(if $(filter Darwin,$(UNAME_S)),1,2)
RELEASE_GATE_PARALLEL ?= $(if $(filter Darwin,$(UNAME_S)),0,1)
PUBLISH_CHECK_JOBS ?= 2
PUBLISH_EVERYWHERE_JOBS ?= 4
XDIST_BENCHMARK_TARGETS ?= $(PY_UNIT_DIR) $(PY_JOURNEY_DIR)
TEST_RUNTIME_ROOT ?= $(ROOT)/var/test-runtime
COV_FAIL_UNDER    ?= 100
COV_SRC           ?= src/mcp_broker
COV_DIR           ?= $(ROOT)/var/coverage
COV_FILE          ?= $(COV_DIR)/.coverage
TEST_LOG_DIR      ?= $(ROOT)/var/test-logs
QUALITY_DIR       ?= $(ROOT)/var/quality
RELEASE_GATE_LOG_DIR ?= $(QUALITY_DIR)/release-gate
GENERATED_SCAN_EXCLUDE_PATHS ?= \
	$(ROOT)/.mutmut-cache \
	$(ROOT)/mutants \
	$(ROOT)/var/public-*check \
	$(ROOT)/var/public-export-check \
	$(QUALITY_DIR)/mutants-* \
	$(QUALITY_DIR)/mutation-linux*.log
VIOLATIONS_JSON   ?= $(QUALITY_DIR)/violations.json
VIOLATIONS_LOG    ?= $(QUALITY_DIR)/violations.log
VIOLATIONS_JOBS   ?= $(LOCAL_CPU_BUDGET)
VIOLATIONS_FLAGS  ?= --no-cache
GRADE_REPORT_JSON ?= $(QUALITY_DIR)/grade_quality_report.json
PACKAGE_DIST_DIR  ?= $(ROOT)/dist
UV                ?= uv
UVX               ?= uvx
NPM               ?= npm
NPX               ?= npx
NPM_DIR           ?= $(ROOT)/npm
PACKAGE_SLUG ?= mcp-broker
GITHUB_OWNER ?= doricstack
PUBLIC_NAMESPACE ?= doricstack
PACKAGE_AUTHOR ?= Navin B Agrawal
NPM_PACKAGE_NAME  ?= @$(PUBLIC_NAMESPACE)/$(PACKAGE_SLUG)
PACKAGE_INSTALL_VERSION ?= $(PACKAGE_VERSION)
DOCKER_IMAGE      ?= $(PACKAGE_SLUG):local
DOCKER_PLATFORM   ?=
DOCKER_PLATFORMS  ?= linux/amd64,linux/arm64
DOCKER_PUSH       ?= 0
DOCKER_SBOM       ?= true
DOCKER_PROVENANCE ?= true
GITHUB_REPO ?= $(GITHUB_OWNER)/$(PACKAGE_SLUG)
GITHUB_REPOSITORY_URL ?= https://github.com/$(GITHUB_REPO)
GITHUB_REPOSITORY_HOST_PATH ?= github.com/$(GITHUB_REPO)
GITHUB_TAG_SOURCE_TARBALL_URL ?= $(GITHUB_REPOSITORY_URL)/archive/refs/tags/v$(PACKAGE_VERSION).tar.gz
PRIVATE_GITHUB_REPO ?= $(GITHUB_OWNER)/$(PACKAGE_SLUG)-private
PRIVATE_GITHUB_REPOSITORY_URL ?= https://github.com/$(PRIVATE_GITHUB_REPO)
DOCKER_SOURCE_URL ?= $(GITHUB_REPOSITORY_URL)
PACKAGE_VERSION   ?= $(shell "$(PYTHON_BIN)" -c 'import json, pathlib, sys; sys.stdout.write(str(json.loads(pathlib.Path("$(ROOT)/npm/package.json").read_text(encoding="utf-8"))["version"]))')
MCP_BROKER_VERSION ?= $(PACKAGE_VERSION)
PACKAGE_MINOR_VERSION ?= $(shell "$(PYTHON_BIN)" -c 'import sys; parts="$(PACKAGE_VERSION)".split("."); sys.stdout.write(".".join(parts[:2]))')
DOCKER_LOCAL_PLATFORM ?= $(if $(filter Darwin,$(UNAME_S)),linux/arm64,linux/amd64)
DOCKER_REGISTRY_HOST ?= docker.io
DOCKER_REGISTRY ?= $(DOCKER_REGISTRY_HOST)
DOCKER_NAMESPACE ?= $(PUBLIC_NAMESPACE)
DOCKER_IMAGE_NAME ?= $(PACKAGE_SLUG)
DOCKER_RELEASE_TAG ?= $(PACKAGE_VERSION)
DOCKER_REPOSITORY_IMAGE ?= $(DOCKER_REGISTRY)/$(DOCKER_NAMESPACE)/$(DOCKER_IMAGE_NAME)
DOCKER_RELEASE_IMAGE ?= $(DOCKER_REGISTRY)/$(DOCKER_NAMESPACE)/$(DOCKER_IMAGE_NAME):$(DOCKER_RELEASE_TAG)
DOCKER_MINOR_IMAGE ?= $(DOCKER_REGISTRY)/$(DOCKER_NAMESPACE)/$(DOCKER_IMAGE_NAME):$(PACKAGE_MINOR_VERSION)
GHCR_REGISTRY_HOST ?= ghcr.io
GHCR_REPOSITORY_IMAGE ?= $(GHCR_REGISTRY_HOST)/$(DOCKER_NAMESPACE)/$(DOCKER_IMAGE_NAME)
GHCR_IMAGE ?= $(GHCR_REPOSITORY_IMAGE):$(DOCKER_RELEASE_TAG)
GHCR_MINOR_IMAGE ?= $(GHCR_REPOSITORY_IMAGE):$(PACKAGE_MINOR_VERSION)
DOCKER_PUBLISH_IMAGES ?= $(DOCKER_RELEASE_IMAGE) $(DOCKER_MINOR_IMAGE) $(GHCR_IMAGE) $(GHCR_MINOR_IMAGE)
DOCKER_HUB_REPOSITORY_URL ?= https://hub.docker.com/v2/repositories/$(DOCKER_NAMESPACE)/$(DOCKER_IMAGE_NAME)/
DOCKER_HUB_RELEASE_TAG_URL ?= https://hub.docker.com/v2/repositories/$(DOCKER_NAMESPACE)/$(DOCKER_IMAGE_NAME)/tags/$(DOCKER_RELEASE_TAG)
DOCKER_HUB_MINOR_TAG_URL ?= https://hub.docker.com/v2/repositories/$(DOCKER_NAMESPACE)/$(DOCKER_IMAGE_NAME)/tags/$(PACKAGE_MINOR_VERSION)
DOCKER_HUB_API_REPOSITORY_BASE_URL ?= https://hub.docker.com/v2/repositories
DOCKER_HUB_API_NAMESPACE_BASE_URL ?= https://hub.docker.com/v2/namespaces
DOCKER_HUB_LEGACY_REPOSITORY_BASE_URL ?= https://hub.docker.com/v2/repositories
DOCKER_HUB_LOGIN_URL ?= https://hub.docker.com/v2/users/login
DOCKER_REGISTRY_SERVICE ?= registry.docker.io
DOCKER_REGISTRY_AUTH_URL ?= https://auth.docker.io/token
DOCKER_REGISTRY_MANIFEST_BASE_URL ?= https://registry-1.docker.io/v2
GHCR_REGISTRY_SERVICE ?= ghcr.io
GHCR_REGISTRY_AUTH_URL ?= https://ghcr.io/token
GHCR_REGISTRY_MANIFEST_BASE_URL ?= https://ghcr.io/v2
DOCKER_MCP_CATALOG_FILE ?= $(ROOT)/docker/mcp-catalog/$(PACKAGE_SLUG).yaml
DOCKER_MCP_CATALOG_REF ?= $(PACKAGE_SLUG)-local-catalog:local
DIRECTORY_SUBMISSION_PACKET ?= $(ROOT)/docs/directory-submission-packet.md
SERVER_CARD_PATH ?= $(ROOT)/.well-known/mcp/server-card.json
REGISTRY_METADATA_PATH ?= $(ROOT)/registry/server.json
PACKAGE_COMMAND_NAME ?= $(PACKAGE_SLUG)
PACKAGE_CLIENT_COMMAND_NAME ?= $(PACKAGE_SLUG)-client
PACKAGE_DAEMON_COMMAND_NAME ?= $(PACKAGE_SLUG)-daemon
PYPI_PROJECT_NAME ?= $(PACKAGE_SLUG)
PYPI_VERSION_URL ?= https://pypi.org/pypi/$(PYPI_PROJECT_NAME)/$(PACKAGE_VERSION)/json
PYPI_PROJECT_URL ?= https://pypi.org/project/$(PYPI_PROJECT_NAME)
PYPI_SIMPLE_CHECK_URL ?= https://pypi.org/simple/$(PYPI_PROJECT_NAME)/
GITHUB_RELEASE_TAG ?= v$(PACKAGE_VERSION)
GITHUB_RELEASE_TITLE ?= $(PACKAGE_SLUG) v$(PACKAGE_VERSION)
GITHUB_RELEASE_URL ?= https://api.github.com/repos/$(GITHUB_REPO)/releases/tags/$(GITHUB_RELEASE_TAG)
GITHUB_RELEASE_LATEST_URL ?= $(GITHUB_REPOSITORY_URL)/releases/latest
GITHUB_RELEASE_NOTES_FILE ?= $(ROOT)/CHANGELOG.md
HOMEBREW_TAP_REPO ?= $(GITHUB_OWNER)/homebrew-tap
HOMEBREW_TAP_REF ?= $(GITHUB_OWNER)/tap
HOMEBREW_TAP_BRANCH ?= main
HOMEBREW_TAP_URL ?= https://github.com/$(HOMEBREW_TAP_REPO)
HOMEBREW_TAP_CLONE_URL ?= $(HOMEBREW_TAP_URL).git
HOMEBREW_FORMULA_PATH ?= Formula/mcp-broker.rb
HOMEBREW_FORMULA_REF ?= $(HOMEBREW_TAP_REF)/$(PACKAGE_SLUG)
HOMEBREW_FORMULA_RAW_URL ?= https://raw.githubusercontent.com/$(HOMEBREW_TAP_REPO)/$(HOMEBREW_TAP_BRANCH)/$(HOMEBREW_FORMULA_PATH)
HOMEBREW_GIT_AUTHOR_NAME ?= $(PACKAGE_SLUG) release automation
HOMEBREW_GIT_AUTHOR_EMAIL ?= actions@github.com
HOMEBREW_PYPI_ATTEMPTS ?= 12
HOMEBREW_PYPI_RETRY_DELAY_SECONDS ?= 10
MCP_REGISTRY_NAME ?= io.github.$(GITHUB_REPO)
MCP_REGISTRY_API_BASE_URL ?= https://registry.modelcontextprotocol.io/v0.1
MCP_REGISTRY_SEARCH_URL ?= https://registry.modelcontextprotocol.io/v0.1/servers?search=$(MCP_REGISTRY_NAME)
MCP_PUBLISHER_RELEASE_DOWNLOAD_BASE_URL ?= https://github.com/modelcontextprotocol/registry/releases/latest/download
NPM_REGISTRY_URL ?= https://registry.npmjs.org
NPM_PACKAGE_URL ?= https://www.npmjs.com/package/$(NPM_PACKAGE_NAME)
DOCKER_HUB_TAGS_URL ?= https://hub.docker.com/r/$(DOCKER_NAMESPACE)/$(DOCKER_IMAGE_NAME)/tags
SMITHERY_QUALIFIED_NAME ?= $(SMITHERY_NAMESPACE)/$(PACKAGE_SLUG)
SMITHERY_LISTING_URL ?= https://smithery.ai/servers/$(SMITHERY_QUALIFIED_NAME)
SMITHERY_API_BASE_URL ?= https://api.smithery.ai
SMITHERY_NAMESPACE ?= $(PUBLIC_NAMESPACE)
SMITHERY_RELEASE_ID ?= aae18669-9500-4a5d-9870-8f9b3bfd404d
SMITHERY_MCP_URL ?= https://$(PACKAGE_SLUG)--$(PUBLIC_NAMESPACE).run.tools
GLAMA_LISTING_URL ?= https://glama.ai/mcp/servers/$(GITHUB_REPO)
GLAMA_MAINTAINER ?= $(GITHUB_OWNER)
GLAMA_SCHEMA_URL ?= https://glama.ai/mcp/schemas/server.json
PULSEMCP_LISTING_URL ?= https://www.pulsemcp.com/servers/$(DOCKER_NAMESPACE)-$(DOCKER_IMAGE_NAME)
PULSEMCP_SUBMIT_URL ?= https://www.pulsemcp.com/submit
MCPSERVERS_LISTING_URL ?= https://mcpservers.org/servers/$(DOCKER_NAMESPACE)/$(DOCKER_IMAGE_NAME)
MCPSERVERS_SUBMIT_URL ?= https://mcpservers.org/submit
MCP_SO_LISTING_URL ?= https://mcp.so/server/$(DOCKER_IMAGE_NAME)/$(GLAMA_MAINTAINER)
MCPCENTRAL_REGISTRY_URL ?= https://registry.mcpcentral.io
MCPCENTRAL_SUBMIT_URL ?= https://mcpcentral.io/submit-server
DOCKER_MCP_CATALOG_PR_URL ?= https://github.com/docker/mcp-registry/pull/3819
PUNKPEYE_AWESOME_PR_URL ?= https://github.com/punkpeye/awesome-mcp-servers/pull/6993
APPCYPHER_AWESOME_FORK_BRANCH_URL ?= https://github.com/$(GITHUB_OWNER)/awesome-mcp-servers-1/tree/add-mcp-broker
APPCYPHER_AWESOME_COMPARE_URL ?= https://github.com/appcypher/awesome-mcp-servers/compare/main...$(GITHUB_OWNER):awesome-mcp-servers-1:add-mcp-broker
PUBLISH_EVERYWHERE_APPLY ?= 0
PUBLISH_EVERYWHERE_SKIP_CHECKS ?= 0
RELEASE_APPLY ?= 0
RELEASE_VERSION ?=
RELEASE_BUMP ?=
EXPECTED_PUBLISH_VERSION ?=
MCPB_MANIFEST     ?= $(ROOT)/mcpb/manifest.json
MCPB_OUTPUT       ?= $(PACKAGE_DIST_DIR)/$(PACKAGE_SLUG)-$(PACKAGE_VERSION).mcpb
MCPB_SMOKE_DIR    ?= $(TEST_LOG_DIR)/mcpb-smoke
MCPB_SMOKE_OUTPUT ?= $(MCPB_SMOKE_DIR)/$(PACKAGE_SLUG).mcpb
MCPB_SMOKE_UNPACK_DIR ?= $(MCPB_SMOKE_DIR)/unpacked
MCPB_STDIO_COMMAND ?= $(VENV_DIR)/bin/mcp-broker
SMITHERY_PAYLOAD_OUTPUT ?= $(TEST_LOG_DIR)/smithery-payload.json
PYTEST_COMMON     ?= --color=yes --force-sugar --maxfail=$(PYTEST_MAXFAIL) --timeout=$(PYTEST_TIMEOUT) $(PYTEST_MARKER_ARGS) $(PYTEST_XDIST_ARGS)
PYTEST_TARGETED_COMMON ?= --color=yes --force-sugar --maxfail=$(PYTEST_MAXFAIL) --timeout=$(PYTEST_TIMEOUT) $(PYTEST_MARKER_ARGS) $(PYTEST_TARGETED_XDIST_ARGS)
PYTEST_LIVE_COMMON ?= --color=yes --force-sugar --maxfail=$(PYTEST_MAXFAIL) --timeout=$(PYTEST_LIVE_TIMEOUT) $(PYTEST_MARKER_ARGS) $(PYTEST_XDIST_ARGS)
PYTEST_COV_COMMON ?= --color=yes --force-sugar --maxfail=$(PYTEST_MAXFAIL) --timeout=$(PYTEST_COV_TIMEOUT) $(PYTEST_COV_MARKER_ARGS) $(PYTEST_XDIST_ARGS)
BROKER_WAIT_SECONDS ?= 10
MUTATION_MAX_CHILDREN ?= $(if $(filter Darwin,$(UNAME_S)),1,$(LOCAL_CPU_BUDGET))
MUTATION_RELEASE_CHILDREN ?= $(if $(filter Darwin,$(UNAME_S)),1,$(shell "$(PYTHON_BIN)" -c 'import sys; sys.stdout.write(str(max(1, int("$(LOCAL_CPU_BUDGET)") // int("$(RELEASE_GATE_JOBS)"))))' 2>/dev/null || printf 1))
MUTATION_ARGS    ?=
MUTATION_IMAGE   ?= python:3.11-bookworm
MUTATION_STATS_JSON ?= $(QUALITY_DIR)/mutation_stats.json
MUTATION_LOG ?= $(QUALITY_DIR)/mutation-linux.log
MUTATION_MUTANTS_DIR ?= $(QUALITY_DIR)/mutants-linux
MUTATION_MIN_SCORE ?= 100
MUTATION_FAIL_STATUSES ?= survived no_tests skipped suspicious timeout check_was_interrupted_by_user segfault not_checked
SHARED_SCRIPTS_DIR ?= $(HOME)/.llm-shared/scripts
CHECK_VIOLATIONS ?= $(SHARED_SCRIPTS_DIR)/check-violations.sh
GRADE_QUALITY    ?= $(SHARED_SCRIPTS_DIR)/grade_quality.sh

PY_UNIT_DIR       ?= tests/unit
PY_JOURNEY_DIR    ?= tests/journey
PY_LIVE_DIR       ?= tests/live
PY_E2E_DIR        ?= tests/e2e
PYTEST_UNIT_TARGETS ?= $(if $(PYTEST_ARGS),$(PYTEST_ARGS),$(PY_UNIT_DIR))
PYTEST_JOURNEY_TARGETS ?= $(if $(PYTEST_ARGS),$(PYTEST_ARGS),$(PY_JOURNEY_DIR))
PYTEST_LIVE_TARGETS ?= $(if $(PYTEST_ARGS),$(PYTEST_ARGS),$(PY_LIVE_DIR))
PYTEST_E2E_TARGETS ?= $(if $(PYTEST_ARGS),$(PYTEST_ARGS),$(PY_E2E_DIR))

export PYTHONPATH := $(ROOT)/src
export MCP_BROKER_VERSION
export COVERAGE_FILE := $(COV_FILE)
export MCP_BROKER_RUNTIME_ROOT := $(RUNTIME_ROOT)
export MCP_BROKER_CONFIG := $(CONFIG_PATH)
export MCP_BROKER_SOCKET := $(SOCKET_PATH)
export MCP_BROKER_LOG_DIR := $(LOG_DIR)
export MCP_BROKER_STATE_DIR := $(STATE_DIR)
export MCP_BROKER_SECRETS_DIR := $(SECRETS_DIR)
